### ISSUE TITLE
Rename project to something generic

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/concourse-infra-for-gke#62]
Suggestions:
- concourse-for-gke
- concourse-for-k8s
- cff-ci-infra

**Comment by rkoster** [comment]
cc @ramonskie, @beyhan

**Comment by beyhan** [comment]
My favourite is `cff-ci-infra` and I would suggest to add also concourse to it because it is about concourse and have `cff-concourse-ci-infra`.

**Comment by ramonskie** [comment]
i would prefer concourse-for-gke or something similar  
as it describes what it actually is a concourse on gke

**Comment by rkoster** [comment]
@beyhan do you have any additional thoughts on `concourse-for-gke`?

**Comment by beyhan** [comment]
I opened the [pr](https://github.com/cloudfoundry/community/pull/515) for the new repo as discussed.
